default.nix, tablecloth/default.nix, tablecloth/metadata.nix
Needs some work.
WIP patches fork: https://github.com/colemickens/tablecloth
=> WIP: tablecloth: add package

README.md
@zimbatm can you test out these instructions, assuming you have an 18.09 system?
rendered view: https://github.com/colemickens/nixpkgs-wayland/blob/usage-18.09/README.md see the "usage" section
=>  README: add usage for nixos-18.09 

README.md, docs/sway-on-ubuntu/README.md, docs/sway-on-ubuntu/execute.sh
Still working on the docs, this will help with a rendered view.
=> nixpkgs: sway on ubuntu

README.md, build.nix, default.nix
https://github.com/colemickens/nixpkgs-wayland/blob/nixpkgs-wayland-readme-pkgs/README.md
=> README: hide/collapse list of packages by default

README.md, pkgs/i3status-rust/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/wlroots/metadata.nix
autoupdates: wlroots, sway-beta, i3status-rust
=> autoupdates: wlroots, sway-beta, i3status-rust

README.md, build.nix
=> build.nix: output set instead of list

README.md, pkgs/fmt/metadata.nix, pkgs/grim/metadata.nix, pkgs/mako/metadata.nix, pkgs/slurp/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wlroots/metadata.nix
=> update: fmt, grim, mako, slurp, sway-beta, waybar, wlroots

README.md, default.nix, pkgs/wl-clipboard/default.nix, pkgs/wl-clipboard/metadata.nix, update.sh
=> wl-clipboard: add package

README.md, pkgs/fmt/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayfire/metadata.nix, update.sh
updates: fmt, sway-beta, waybar, wayfire
=> updates: fmt, sway-beta, waybar, wayfire

build.nixpkgs.nix, nixpkgs/nixpkgs-unstable/default.nix, nixpkgs/nixpkgs-unstable/metadata.nix, update.sh
cc: @zimbatm 
doing this for the "sway on ubuntu" (or rather non-nixos) path/users...
=> build for nixpkgs-unstable also

README.md
Fixes #33 in a more immediate fashion than the full blown demo.
=> docs: add sway tips

README.md
I think 'the' is not needed here.
=> README.md: remove unneeded 'the'

README.md, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/fmt/metadata.nix, pkgs/kanshi/default.nix, pkgs/kanshi/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayfire/metadata.nix
=> updates: numerous

README.md, nixpkgs/nixos-unstable/metadata.nix, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/fmt/metadata.nix, pkgs/mako/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/wayfire/metadata.nix, pkgs/wlroots/metadata.nix
=> update: fmt, mako, sway-beta, wayfire, wlroots

README.md, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/mako/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/wlroots/metadata.nix
=> update: mako, sway-beta, wlroots

README.md, pkgs/sway-beta/metadata.nix, pkgs/wl-clipboard/metadata.nix, pkgs/wlroots/metadata.nix, pkgs/wmfocus/metadata.nix
=> update:: wlroots, sway-beta, wl-clipboard, wmfocus

README.md, pkgs/fmt/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/wayfire/metadata.nix
=> update: fmt, sway-beta, wayfire

README.md, nixpkgs/nixos-unstable/metadata.nix, pkgs/fmt/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/swayidle/default.nix, pkgs/waybar/default.nix, pkgs/waybar/metadata.nix, pkgs/wl-clipboard/metadata.nix, pkgs/wlroots/metadata.nix
=> update: fmt, sway-beta, waybar, wl-clipboard, wlroots

README.md
=> swayidle: document using pkg

README.md, nixpkgs/nixos-unstable/metadata.nix, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/swayidle/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayfire/metadata.nix, pkgs/wlroots/metadata.nix
=> update: sway-beta, swayidle, waybar, wayfire, wlroots

README.md, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/wlroots/metadata.nix
=> update: wlroots

README.md, pkgs/grim/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/swayidle/metadata.nix, pkgs/swaylock/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayfire/metadata.nix, pkgs/wlroots/metadata.nix, pkgs/wmfocus/metadata.nix
note: wl-clipboard was held back due to build failures.
see: https://github.com/bugaevc/wl-clipboard/issues/29
=> update: grim, sway{-beta,idle,lock}, waybar, wayfire, wlroots, wmfocus

default.nix, pkgs-temp/scdoc/default.nix
Well, I'd already done this once, but I must have fixed it in the commit I pushed to master and reverted, so here it is again.
=> sway: fix by adding scdoc temporarily

README.md
=> README: add swaylock

README.md, build.nixos-unstable.nix, build.nixpkgs-unstable.nix, pkgs/sway-beta/metadata.nix, pkgs/wl-clipboard/metadata.nix, pkgs/wlroots/metadata.nix
NOTE: This unpins `wl-clipboard` now that https://github.com/bugaevc/wl-clipboard/issues/29 is fixed.
=> update: sway-beta, wl-clipboard, wlroots

README.md, pkgs/sway-beta/metadata.nix
=> update: sway-beta

README.md, nixpkgs/nixos-unstable/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/wayfire/metadata.nix
=> update: sway-beta, wayfire

README.md, pkgs/sway-beta/metadata.nix, pkgs/wlroots/metadata.nix
=> update: wlroots, sway-beta

README.md, pkgs/slurp/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wlroots/metadata.nix
=> update: slurp, sway-beta, waybar, wlroots

README.md, nixpkgs/nixos-unstable/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wmfocus/default.nix, pkgs/wmfocus/metadata.nix
=> update: sway-beta, waybar, wmfocus

README.md, nixpkgs/nixos-unstable/metadata.nix, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/sway-beta/metadata.nix
=> update: sway-beta, nixpkgs

README.md, nixpkgs/nixos-unstable/metadata.nix, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/slurp/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/swaylock/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayfire/metadata.nix, pkgs/wf-config/metadata.nix, pkgs/wl-clipboard/metadata.nix, pkgs/wlroots/metadata.nix
=> update: slurp, sway-beta, swaylock, waybar, wayfire, wf-config, wl-clipboard, wlroots

pkgs/waybar/default.nix
Fixes the problem #104 tried to address.
=> waybar: fix etc outputs

README.md, pkgs/sway-beta/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayfire/metadata.nix, pkgs/wlroots/metadata.nix
=> update: sway, waybar, wayfire, wlroots

README.md, nixpkgs/nixos-unstable/metadata.nix, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/sway/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wlroots/metadata.nix
=> update: sway, waybar, wlroots

default.nix, pkgs/swaybg/default.nix, pkgs/swaybg/metadata.nix, update.sh
Fixes issue #141
I have tried to package swaybg pretty much by copying the format for the grim package already in the repository. I have checked that my background now works with this installed to my system. Also have tried to update the `update.sh` file though I'm not sure if I have done this correctly
=> Swaybg: init package

README.md, default.nix, pkgs/wofi/default.nix, pkgs/wofi/metadata.nix
=> wofi: init

README.md, default.nix, pkgs/clipman/default.nix, pkgs/clipman/metadata.nix
=> clipman: init

.envrc, default.nix, pkgs/emacs/default.nix, pkgs/emacs/metadata.nix
=> emacs: init pgtk

README.md
@colemickens quick fix & merge :smile:
=> doc: clarify obs-xdg-portal dependency on obs-studio-dmabuf

README.md, flake.nix, pkgs/dunst/default.nix, pkgs/dunst/metadata.nix
=> dunst: init at 77bfbc4f7ff

flake.nix, pkgs/imv/default.nix, pkgs/imv/metadata.nix
=> imv: update derivation, un-skip

pkgs/sway/default.nix, pkgs/sway/fix-paths.patch
Should fix https://github.com/colemickens/nixpkgs-wayland/issues/270. 
This builds but I haven't tested that it fixes the issue yet
=> Fix sway-bg path

flake.nix, pkgs/sirula/default.nix, pkgs/sirula/metadata.nix
Add a new package: sirula
Attempted to follow the pattern as best I could. Saw #235 and decided I wanted to try the application, so I packaged it up and thought I'd contribute back. I believe this should be auto-updatable based on my limited reading of the various scripts.
Feedback most definitely welcomed.
Fixes #235
=> sirula: add package

pkgs/wdisplays/metadata.nix
See https://github.com/colemickens/nixpkgs-wayland/issues/287#issuecomment-816218540
See #264
=> wdisplays: update upstream branch to fix-global-version

pkgs/xdg-desktop-portal-wlr/default.nix, pkgs/xdg-desktop-portal-wlr/metadata.nix
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/xdg-desktop-portal-gtk/default.nix
=> xdg-desktop-portal-wlr: update expression and unpin

flake.nix, pkgs/wlogout/default.nix
supersedes https://github.com/nix-community/nixpkgs-wayland/pull/258
gtk-layer-shell support in nixpkgs https://github.com/NixOS/nixpkgs/pull/144866
=> wlogout: switch to a override

README.md, flake.nix, pkgs/foot/default.nix, pkgs/foot/metadata.nix
=> foot: init at 55c5f0590e487825431ca9c87fa68100f87358d1

flake.nix, pkgs/cage/default.nix, pkgs/cage/metadata.nix
=> cage: fix build and switch to a override

pkgs/obs-wlrobs/default.nix
=> update wlr-obs URL

flake.lock, flake.nix, pkgs/grim/default.nix, pkgs/oguri/default.nix, pkgs/slurp/default.nix, pkgs/swaybg/default.nix, pkgs/swayidle/default.nix, pkgs/swaylock/default.nix, pkgs/wf-recorder/default.nix, pkgs/wl-clipboard/default.nix, pkgs/wlfreerdp/default.nix
cachix input had to be updated because that version of nixpkgs still had url literals
=> remove url literal

flake.lock, flake.nix
use flake-utils
fix statix lints
inherit instead of assign
format alejandra
=> flake.nix: simplify

README.md, flake.nix, pkgs/wayprompt/default.nix, pkgs/wayprompt/metadata.nix
this builds now, not thoroughly tested though
=> wayprompt: init at 8a6fe7d1d3e8fb6cb54733a0cb10be521c0a72b4

pkgs/foot/default.nix, pkgs/foot/metadata.nix
=> fix foot build

flake.nix, pkgs/salut/default.nix, pkgs/salut/metadata.nix
=> salut: init at 2c2d8e325adae3b134dbe6275673b8235cae3663

flake.nix
Nixpkgs now pulls in patches from the git repo, remove them.
=> flake: gtk-layer-shell: remove patches

pkgs/wlr-randr/metadata.nix
=> wlr-randr: move to gitsourcehut

README.md, flake.nix
we've warned for a long time and are past due to remove it
=> wlfreerdp: finally drop alias

flake.lock, flake.nix
See https://github.com/NixOS/nixpkgs/pull/273762
=> sway-unwrapped: update wlroots override

pkgs/wlroots/default.nix
https://github.com/NixOS/nixpkgs/pull/276322
=> wlroots: don't need check conflicting-patch now

flake.nix
=> cage: remove xwayland meson flag

pkgs/kanshi/metadata.nix
It updates + builds when I unskip, so... here we go!
=> kanshi: unskip

flake.nix
broke again due to a new dependency.
i'd like to refer back to #449.
it seems like even upstream the build fails from time to time, but there are people taking care of it. see: https://github.com/Alexays/Waybar/pull/4219
so we're basically doing duplicate work here.
=> waybar: fix update by adding gpsd
