README.md, default.nix, i3status-rust/0001-Cargo.lock-regenerate.patch, i3status-rust/default.nix, i3status-rust/metadata.nix, update.sh
Currently failing:
```
building '/nix/store/8dbx2sm888nn0sw5cmqjfdxylmy2513x-i3status-rust-2b3ccf48721b3944281ee44a7e7562083471062d-vendor.drv'...
unpacking sources
unpacking source archive /nix/store/n78zcmpjvcgggs8vcgj0r4giz0hsj9qy-source
source root is source
patching sources
installing
error: failed to sync
Caused by:
failed to load pkg lockfile
Caused by:
failed to parse lock file at: /build/source/Cargo.lock
To learn more, run the command again with --verbose.
Traceback (most recent call last):
File "/nix/store/d9malik4cg6za7d45gb86yl3rrrscvmv-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
main()
File "/nix/store/d9malik4cg6za7d45gb86yl3rrrscvmv-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
assert list(data.keys()) …
```
=> i3status-rust: init package

README.md, docs/sway-on-ubuntu/README.md, docs/sway-on-ubuntu/execute.sh
This will:
* fixup the documentation for "Sway on Ubuntu"
* remove support (aka documentation) for 18.09. we already stopped building and caching the packages a few days ago, dropping docs reduces support burden
cc: @zimbatm
=> fixup sway-on-ubuntu, drop 18.09 support

default.nix, pkgs/swayidle/default.nix, pkgs/swayidle/metadata.nix, update.sh
swayidle has been split out of sway in https://github.com/swaywm/sway/commit/bc808680b173d5a3c4732265b33e2e8bd81e4d9b
=> swayidle: init at 2019-01-13T01:50:02Z

pkgs/swayidle/default.nix
Fixes #75 by adding `systemd` support to `swayidle`, thus letting it support `before-sleep`.
=> swayidle: add systemd

README.md, default.nix, nixpkgs/nixpkgs-unstable/metadata.nix, pkgs/sway-beta/metadata.nix, pkgs/swayidle/metadata.nix, pkgs/swaylock/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayfire/metadata.nix, pkgs/wl-clipboard/metadata.nix, pkgs/wlroots/metadata.nix
This should also resolve #79 by re-enabling `wayfire`.
(Fixes #79.)
=> update: sway-beta, swayidle, swaylock, waybar, wayfire, wl-clipboard, wlroots

README.md, default.nix, pkgs/wlr-randr/default.nix, pkgs/wlr-randr/metadata.nix
Builds and runs:
```bash
$ $(nix-build build.nix -A nixosUnstable.wlr-randr)/bin/wlr-randr
eDP-1 "Sharp Corporation 0x148B 0x00000000 (eDP-1)"
Physical size: 290x170 mm
Enabled: yes
Modes:
3840x2160 px, 59.997002 Hz (preferred, current)
3840x2160 px, 47.997002 Hz
Position: 3440,0
Transform: normal
Scale: 3.000000
DP-2 "Dell Inc. Dell AW3418DW #ASPD8psOnhPd (DP-2)"
Physical size: 800x340 mm
Enabled: yes
Modes:
3440x1440 px, 59.973000 Hz (preferred, current)
3440x1440 px, 120.000000 Hz
3440x1440 px, 100.000000 Hz
3440x1440 px, 84.963997 Hz
3440x1440 px, 49.987000 Hz
1024x768 px, 60.004002 Hz
800x600 px, 60.317001 Hz
640x480 px, 60.000000 Hz
640x480 px, 59.939999 Hz
Position: 0,0
Transform: normal
Scale: 1.000000
```
=> wlr-randr: init

README.md
I think the description of `slurp` got accidently copied to `grim` here?
=> Readme: fix description of grim

pkgs/wlogout/default.nix
wlogout would exit upon loading because it would fail to find its
configuration files (`layout` and `style.css`) in either `$XDG_CONFIG_HOME`
(which does not exist until the user creates the `wlogout` directory under
`$XDG_CONFIG_HOME`) or in its hardcoded static path.
=> wlogout: fix hardcoded configuration path in program

pkgs/sway/default.nix
```
$(nix-build build.nix -A sway-unwrapped)/bin/sway --version
sway version 1.4-c0811fcf8736961725f7aa848e740f38f2bdf6ed (2020-03-04 03:09:43 +0100, branch 'master')
```
seems a bit wordy, not sure the version is necessary.
cc @cole-h
=> sway: patch version

.envrc, .gitignore, flake.lock, flake.nix, shell.nix, update-flakes.sh, update.sh
This effectively converts the repo into a package set and adds flake support.
This is blocked on updated usage instructions that show how to use it as an overlay (so users can continue using it the same way they do now). This may require another output in the flake.
=> Flakes support (and package set conversion)

pkgs/wlroots/default.nix
wlroots examples link to `libwlroots`, which isn't in the search path of either `buildInputs` or `$examples/lib`, so they were failing to start.
Just removing the `patchelf` command fixes it.
=> fix rpath for wlroots examples

README.md, pkgs/gebaar-libinput/default.nix, pkgs/gebaar-libinput/metadata.nix
The fork of `gebaar-libinput` has some additional features `gebaar-libinput` lacks.
This PR updates the branch from master to that of the PR.
Fork - https://github.com/osleg/gebaar-libinput-fork
Original - https://github.com/Coffee2CodeNL/gebaar-libinput
I was cleaning up my Sway configuration and wondered what gebaar-libinput did.
=> Update gebaar-libinput to use latest changes from the fork

pkgs/wdisplays/default.nix
wdisplays hasn't been working with Sway since Sway 1.5
See https://github.com/cyclopsian/wdisplays/pull/20
=> wdisplays: add patch for cyclopsian/wdisplays#20

pkgs/waypipe/default.nix
Prior to this change, when using the `waypipe ssh ...` form to run
waypipe, waypipe would fail to run ssh due to the path being hardcoded
to /usr/bin/ssh.
This change adds openssh as a dep and uses it to patch the hardwired
/usr/bin/ssh in waypipe.c.
https://gitlab.freedesktop.org/mstoeckl/waypipe/-/blob/cb173d0d9962a2e40001ec936ce72647b5d6a5ee/src/waypipe.c#L775
=> waypipe: nixify hardwired /usr/bin/ssh

pkgs/wlroots/default.nix
The logind backend has been removed from wlroots, instead libseat is
used. Add libseat to support logind on NixOS.
=> wlroots: add libseat dependency

pkgs/wlroots/default.nix
The tinywl package in nixpkgs [uses the wlroot package’s version attribute directly](https://github.com/NixOS/nixpkgs/blob/586a9e6bffb1b4e0e444bf4013169d8f415f2987/pkgs/applications/window-managers/tinywl/default.nix#L7).
=> Use pname+version attributes instead of name in wlroots

README.md
Given that the mentioned code was removed with #317, the readme should be updated accordingly.
=> readme: remove outdated egl section

flake.lock, pkgs/i3status-rust/metadata.nix
Fixes this error;
```
error: hash mismatch in fixed-output derivation '/nix/store/pd3dc7kpw3wwzwans41lqpjaf999xxx1-i3status-rust-0.21.4-vendor.tar.gz.drv':
specified: sha256-KIU0YWxlYL5GVOVAQZddg3PvE3qCnlukPmWgAU9sCO0=
got:    sha256-tNwf2ShnzoSrb1R/g0hOGwQMulWYXyVCILU3Jb+Sfpg=
```
=> i3status-rust: update the cargoSha256

templates/template.nix
format is similar to RFC https://github.com/NixOS/rfcs/pull/107
+g is not used because we also have hg sources
fixes https://github.com/nix-community/nixpkgs-wayland/issues/282 (though i couldn't replicate the issue (but it still fixes builtins.parseDrvName))
=> template.nix: change version format to `+${substring 0 7 metadata.rev}`

README.md, flake.nix, pkgs/oguri/metadata.nix, pkgs/swww/default.nix, pkgs/swww/metadata.nix
These changes replace oguri with swww, as oguri is no longer maintained.
Fixes #389
As noted in the package definition, swww has tests that rely on a wayland env and attempts to connect to the socket.  
To get a successful build I set `doCheck = false` for now. Is there a common convention for this case?
=> swww: init at 0.1.7

flake.nix
This reverts commit 30ddf7595b1e4f063e892ddd886596bc346c4f85.
nixpkgs spdlog uses spdlog_9 as its input now.
See https://github.com/NixOS/nixpkgs/commit/48c25dcaf2deb249615707a310af23ccb42b04c3
=> Revert "waybar fix build"

README.md, flake.nix, pkgs/wl-screenrec/default.nix, pkgs/wl-screenrec/metadata.nix
I just bumped this in `nixpkgs` and figured I'd add it here too.
I don't think we have an example of a rust package that just overrides the version from nixpkgs.
I don't fully grok what the huge difference is but the mechanism used here uses IFD for Cargo.lock vs in nixpkgs it's still using `cargoHash`.
=> wl-screenrec: init at unstable-2023-09-17

flake.nix, templates/template.nix
Closes nix-community/nixpkgs-wayland#426
This allows our packages to replace attributes while still being able to access the original attributes.
Most notably, this allows us to use the final `oldAttrs` including all following `.override` calls.
=> template.nix: allow replace with oldAttrs param

pkgs/swaylock-effects/metadata.nix
jirutka/swaylock-effects is a fork of mortie/swaylock-effects that supports `ext-session-lock-v1`, which supersedes `wlr-input-inhibitor-unstable-v1`, the latter being deprecated for a long time and recently removed from wlroots
=> swaylock-effects: mortie fork -> jirutka fork

pkgs/wlroots/default.nix
Closes #434
See https://github.com/NixOS/nixpkgs/commit/3e1dba866f8346b38bc236483b1d80cee352be3d
=> wlroots: exclude upstream backport patch

flake.nix
https://github.com/NixOS/nixpkgs/commit/36e51d7cbfc920f3e51a5b234f0f35c4b03c8ba7 changed the input name to wlroots, we are providing wlroots_0_16 still
=> sway-unwrapped: wlroots_0_16 -> wlroots

flake.nix
"wlroots" was moved to aliases.nix in https://github.com/NixOS/nixpkgs/pull/252816. wlroots = wlroots_0_18 in aliases.nix, so I used that here.
=> wlroots moved to alias in nixpkgs, use wlroots_0_18

flake.nix
This backs out commit c8a379fc7777f2ba726625ce88a48ec5809125d5.
I don't know what's up, I keep quite confusing myself.
When I tried to remove mesonFlags properly, or filter out the Xwayland flag, I just couldn't get it.
=> Back out "cage: remove xwayland meson flag"

pkgs/dunst/metadata.nix, pkgs/foot/metadata.nix, pkgs/freerdp3/metadata.nix, pkgs/i3status-rust/metadata.nix, pkgs/neatvnc/metadata.nix, pkgs/shotman/metadata.nix, pkgs/slurp/metadata.nix, pkgs/sway-unwrapped/metadata.nix, pkgs/waybar/metadata.nix, pkgs/wayvnc/metadata.nix, pkgs/wbg/metadata.nix, pkgs/wlroots/metadata.nix
For some reason there's some weird dependency ordering. `wlroots` needs to be updated before `waybar`.
So, I did that locally, pushing to unblock updates.
=> manual "auto"-updates

flake.nix, pkgs/waybar/metadata.nix
the waybar build is currently broken when advancing (see [actions/advance](https://github.com/nix-community/nixpkgs-wayland/actions/runs/11191869115/job/31115317900))
the [fix attempt](https://github.com/nix-community/nixpkgs-wayland/commit/a40e6b047b6166aed5fab801e99a8d6b980d4680) by @Artturin was unsuccessful.
i tested the following:
- build `cad18f39` with just the fix
- build `280f11e2` with just the fix
- build `280f11e2` with updated nixpkgs (not contained in this MR)
for some context:
- `libjack2`, `playerctl` and `upower` are already defined buildinputs in nixpkgs
- the whole  `(lib.remove (lib.elemAt previousAttrs.buildInputs 27)` thing effectively removed `upower`, as the length and order of the buildinputs has long changed in nixpkgs
cc @Artturin
=> Fix waybar

flake.nix, templates/template.nix
as discussed in #476 this adds a removal warning for waybar.
i didnt find a good way to add the warning cleanly to `flake.nix` so i added a general solution for adding deprecation-warnings to `template.nix`
=> Deprecation warning waybar
